spring:
  profile: dev  
  jpa:
    hibernate:
      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/USERS?autoreconnect=true"
    username: root
    password: root